os: linux
dist: trusty
group: stable
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- echo "todo"
deploy:
  provider: pypi
  user: "chestm007"
  on:
    branch: master
    tags: true
  password:
    secure: ibOtuhq9zG9AaVzC5mMoKKJsyCH7vXHAWGDRzXPdZbzt5B4SuXeTPAYUigNcBIqAKnoUUM+OWy8Fs5TtNtfkdVpAQ8ZhVqapqdEfDomyR5jm+rfa6IjI3ApEk13FCm0nEsRUoUFZaQ5RRNx/T9Rc0gP69zgypBtsYCqFJTbznE2phThlDKMRQYjhjelAlYFyb3LTPEkzY0anwL7oDUe9NmBrOsH0UcXH48lRk75RxZAf+5GKcSUtHsphRX4xJNvbR+vMYf273D6njeydtaYUIil9EdfaB4o9fZ/yJP2zpYuqjyGvBtm8fseXtyYOsKLkCd9+bbkvxjMdVbmcm6BkF44GmsRewb5VKohFr+Pv2fv2GdwfJE5TgLd5Ddf0HiG8JwXR1tTqCYN4pd4PV9NTGls+5xFinybknPMmUZBoexlk6XT3ou6lhWRRIawGhYtpZtnwY/rcr4vvX97Im2+ioPQEILFq/gKtHLm+QqCQb1/y3uA0OTcSeVnhQCiMPCY/0yj3MnVxASM2z8NJJ142qT5hF8yZF7BSGzDvWSfJc5zfZs8RcJBEO9+59MIrJKJJY03ioZ8zUUszBvAIfO680bpO849cmkIXjqIHMYeCIVDAabz2dfpfAItxqPPfRm1VaLSlJFITTfS/gnpKrwgLMSmGeD+M5fES+Z4EWnrXDJ4=
