python3_install: &python3_install
  run:
    name: install in virtualenv
    command: |
      pip3 install virtualenv
      python3 -m venv venv
      . venv/bin/activate
      pip3 install -r requirements.txt

deploy: &deploy
  run:
    name: deploy to pypi
    command: |
      . venv/bin/activate
      echo -e "[pypi]" >> ~/.pypirc
      echo -e "username = chestm007" >> ~/.pypirc
      echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      pip3 install twine
      python3 setup.py sdist
      twine upload dist/*

version: 2
jobs:
  python3.6:
    docker:
      - image: circleci/python:3.6.8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *python3_install
  deploy:
    docker:
      - image: circleci/python:3.6.8-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *python3_install
      - <<: *deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - python3.6
      - deploy:
          requires:
            - python3.6
